### PR TITLE
Changed API Key

### PR DESCRIPTION
**Pull request by Trauma-Mama**

### CODE REVIEW

**Review by Trauma-Mama — COMMENTED** [review]
Updated API key

**Comment by RuurdBijlsma** [comment]
Hello,
Are you sure you want to merge this into the main repo? I've had this pull request before and the author of the request then accidentally created the pull request, so I'm asking to make sure you intentionally did this

**Comment by Trauma-Mama** [comment]
It was indeed an accident. I'm sorry. Git Hub was not very user-friendly as
someone who has never coded a thing in my life. Enjoy your night

**Comment by Trauma-Mama** [comment]
I was trying to figure out how to push my new api key

**Comment by RuurdBijlsma** [comment]
No problem, have a nice night

**Comment by Trauma-Mama** [comment]
If you don't mind the suggestion, you might want to add to the instructions
to not to forget to rename the repository to your username. I got stuck on
that part for nearly 2 hours

**Comment by RuurdBijlsma** [comment]
I added it to the readme :)

**Pull request closed without merging**
