### PR TITLE
New key

### PR DESCRIPTION
**Pull request by kskwarek**

### CODE REVIEW

**Comment by RuurdBijlsma** [comment]
Hello thanks for the request, I would merge this but you closed it. If you don't want to offer your api key anymore that's fine, but if you do I'd love to merge this

**Comment by kskwarek** [comment]
Sorry, I messed something up when creating my fork, just wanted to make a
quick fork for me and a couple of friends, so I won't give you the key.
Anyway, thanks a lot for your hard work creating this project, wish you
best of luck with v2. You should put up a donation link on your Github.

**Comment by RuurdBijlsma** [comment]
Ok!

**Comment by RuurdBijlsma** [comment]
I added a custom API key setting to the new locationestimatr in case you're interested (https://locationestimatr.web.app) you can fill in your API key there

**Comment by kskwarek** [comment]
Wow, thanks!

**Pull request closed without merging**
